### ISSUE TITLE
논의해볼 사항들

### ISSUE THREAD

**Issue by hye-on** [Wake-up-together-TogetUp/togetup-server#142]
## ☀️설명
> 논의해볼 사항들과 반영해야 할 변경 사항들입니다.

## ☀️논의 사항
- [ ] command, query 폴더 분리
- [ ] pr , 답글 n 일 이상 안볼시 어떻게 할지 - (ex) 머지할 수 있게 하기 )

## 찬미
- [ ] 이미지 압축 코드 삭제

## 혜온
- [ ] TOGETUP_2024_DEV_APPLICATION 시크릿 이름 수정 
- [ ] 이벤트 패키지 위치 수정 - common/event로

**Comment by 05AM** [comment]
자잘하게 논의할 사항이 있는 것 같아 기술적인 문제인 command와 query에 관한 의견을 각자 코멘트로 정리한 후에 회의하는 건 어떨까요?

**Comment by hye-on** [comment]
###  command와 query를 분리
cqrs패턴 자체가 command와 query를 분리하는 것인데  (낮은 수준에서는 폴더,더 높은 수준에서는 db, 사용 기술을 분리)
command와 query폴더를 분리하지  않아야 하는 이유가 있는지 궁금합니다.
command와 query를 분리하는 것이 패턴의 의도를 따르며 응집도를 높인다고 생각합니다.

(같이 스터디한 책의 레포에서도  command와 query를 폴더를 분리하며 설명하고 있습니다.)
https://github.com/madvirus/ddd-start2

### 작업 방식
협업 방식에 대해 제안합니다.
당장  해야할 일을 이슈에 적고 진행하고 있지만, 앞으로 계획이 어떤지 동기화가 되지 않고 논의가 부족하다고 생각이 듭니다.

각각 맡은 도메인의 리팩토링은 그대로 진행하고 , 앞으로 2주 (회의가 2주 간격이라서)단위로 해야 할 일을 같이 논의한 후 분담하면 어떨까요?  

ex) 
알람 리팩토링 -> 찬미
oauth 리팩토링 -> 혜온

---
#### 2주동안 할 일 
- 미션 n회 이상 제안
- 부하테스트 
- db 마이그레이션
- 00이슈 해결
- 레디스 붙이기

**Comment by hye-on** [comment]
패키지 분리에 대한 의견이 같았네요

차이가 나는 부분이  "읽기, 쓰기 모델을 최적화하는 도메인" 의 기준인 것 같아요
저는 커멘트 서비스 , 쿼리서비스가 있는 도메인이 패키지 분리가 되야한다고 생각했습니다.

아래 댓글로 남겨주신 "서비스의 기능을 구분한다는 의미" 로 쿼리서비스라고 하셨는데 어떤 기능을 구분하는지 궁금합니다.
또한 읽기 기능을 구분한다는 의미가 없는지, 있다면 command, query를 구분하는 것과 어떤 점이 다르다고 생각하셨는지 궁금합니다!

![image](https://github.com/Wake-up-together-TogetUp/togetup-server/assets/68319395/e7369da5-e63d-4f5c-aa0d-ea294374f536)


> 의논하고 싶은 부분은 cqrs 패턴 적용시에 서비스명을 어떻게 할지 정하면 좋을 것 같습니다

000커멘드 서비스, 000쿼리 서비스로 해도 좋을 것 같습니다!

**Comment by 05AM** [comment]
cqrs 패턴에 대해 의견만 적고 회의에서 논의하려고 생각했는데, 글이 길어질 것 같아 코멘트로 먼저 정리해두겠습니다!

제 생각와 관련 글들을 종합하여 말씀드리자면 cqrs 패턴을 적용하는 이유는 쿼리와 커맨드 시에 다른 것을 사용하기 때문입니다.

예를 들어 jpa에서는 entity를 다르게 사용한다던지, query/command 패키지별로 db를 다르게 사용한다던지의 방법이 있을 것 같습니다.

그런데 쿼리와 커맨드의 실행에서 다른 점이 없는 도메인에 굳이 패키지를 나눌 필요는 없다고 생각합니다.

만일 저희가 단일 jpa 엔티티를 사용하고 있는 상황에서 query와 command로 패키지를 분리하고 각각 controller, service, domain을 정의한다면 해당 엔티티는 어디에 위치해야 할지 의문이 드는 것 같습니다.

그래서 저의 의견은 명확히 cqrs 패턴을 적용하여 query와 command 사이에 다르게 적용하고 있는 부분이 있는 도메인을 해당 구조로 패키지를 나눴으면 좋겠습니다!

그렇지 않은 상황에서 패키지만 나누는 것은 구조의 복잡도를 높이는 원인이 될 것 같습니다.
