### ISSUE TITLE
객체지향적인 프로그래밍과 가독성을 위한 코드 컨벤션 정하기

### ISSUE THREAD

**Issue by 05AM** [Wake-up-together-TogetUp/togetup-server#74]
## ☀️한줄 요약

> 객체지향적인 프로그래밍과 가독성을 위한 코드 컨벤션 정하기

## ☀논의 내용

사실 저희가 빠르게 개발하다 보니 가독성이나 객체 지향적인 면을 고려하지 않고 진행하고 있는 것 같습니다.
하지만 가독성이 떨어지다 보니 코드 리뷰에도 시간이 걸리고, 서로의 코드에 대한 이해도가 떨어지는 것 같다고 생각합니다.

그래서 간단하게 도입하고 싶은 것이 `메소드 추출`과 `setter` 사용 자제입니다! 메소드 추출은 각 메소드의 기능을 명확하게 하며 가독성을 높이고, setter은 객체가 어디에서나 예기치 않게 변경되지 않는다는 장점이 있습니다.

또한 코드 포맷팅 완료 후 pr 생성하는 컨벤션 도입을 희망합니다. 이를 도입한다면 가독성도 높이고, 머지 시 충돌할 위험도 감소한다고 생각합니다.

> 위의 컨벤션 도입에 대해서 어떻게 생각하시는지, 새롭게 도입하고 싶으신 컨벤션이 있는지 의견을 듣고 싶습니다.

**Comment by hye-on** [comment]
좋아요!
roomService 122번째 줄 setUserLogData 같은 경우는 setter를 어떻게 대체하면 좋을까요??
비지니스 로직 후에 dto를 세팅할때는 어떻게 하면 좋을지 고민이네요!

**Comment by 05AM** [comment]
> 좋아요! roomService 122번째 줄 setUserLogData 같은 경우는 setter를 어떻게 대체하면 좋을까요?? 비지니스 로직 후에 dto를 세팅할때는 어떻게 하면 좋을지 고민이네요!

setter를 대체하는 방법에 대해서 찾아보시면 좋을 것 같아요!

dto를 제외한 model 객체는 불변한 상태를 유지하는 것이 좋기 때문에 생성자로 새로운 객체를 생성하거나, set~이 아닌 무엇을 하는지 명시하는 이름의 함수를 만드는 것도 방법이라고 생각해요

**Comment by hye-on** [comment]
처음에 제안한 setter 지양이 dto에도 적용되는 줄 알고 질문드렸었어요

https://www.inflearn.com/questions/161417/dto-%EC%82%AC%EC%9A%A9%EC%97%90%EB%8C%80%ED%95%B4-%EA%B6%81%EA%B8%88%ED%95%A9%EB%8B%88%EB%8B%A4

링크보니까 dto에서는 setter 사용해도 되네요. 답변 감사합니다!
