### ISSUE TITLE
[ENV] Dn 룰 도입을 제안합니다.

### ISSUE THREAD

**Issue by 05AM** [Wake-up-together-TogetUp/togetup-server#98]
## ☀️설명

- Dn룰은 PR을 언제까지 리뷰해달라는 요청을 라벨로 명시하는 것 입니다. 위 규칙의 도입을 제안합니다.

## ☀️참고 사항

![image](https://github.com/Wake-up-together-TogetUp/togetup-server/assets/83827023/445824b2-a398-4557-b08c-ba5a149aa941)

**Comment by hye-on** [comment]
좋아요~~ 👍
